kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jupyterlab.fullname" . }}
  labels:
    app: {{ template "jupyterlab.name" . }}
    chart: {{ template "jupyterlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}