apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  jupyterPassword: {{ .Values.jupyterPassword | b64enc | quote }}