apiVersion: v1
kind: Service
metadata:
  name: {{ include "master.fullname" . }}
  labels:
    {{- include "master.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: spark
      protocol: TCP
      name: spark
  selector:
    {{- include "master.selectorLabels" . | nindent 4 }}
